# Run at repo root to generate: vhs ./assets/demo.tape
# Docs: https://github.com/charmbracelet/vhs

Output assets/demo.gif

Set Shell "bash"
Set FontFamily "UbuntuMono Nerd Font Mono"
Set FontSize 22
Set Width 1200
Set Height 800
Set Padding 0
Set WindowBar "Colorful"
Set Theme "Dracula"

Sleep 250ms
Type "pim" 
Sleep 250ms
Enter
Sleep 1500ms

Type "See which file/function will benefit the most from a unit test. Then write one for it."
Sleep 250ms
Enter
Sleep 180s
